name: 🐛 Bug Report
description: Сообщить об ошибке в скрипте установки или конфигурации
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - samtj24
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за помощь в улучшении проекта! 
        Пожалуйста, заполните форму максимально подробно.

  - type: checkboxes
    id: terms
    attributes:
      label: Предварительные проверки
      description: Перед отправкой отчета убедитесь, что выполнили следующие шаги
      options:
        - label: Я проверил [документацию](https://github.com/samtj24/Install.sh/blob/main/GUIDE.md)
          required: true
        - label: Я просмотрел [существующие Issues](https://github.com/samtj24/Install.sh/issues)
          required: true
        - label: Я попробовал решения из [Troubleshooting](https://github.com/samtj24/Install.sh/blob/main/docs/troubleshooting.md)
          required: true

  - type: dropdown
    id: script_type
    attributes:
      label: Какой скрипт используется?
      description: Выберите скрипт, с которым возникла проблема
      options:
        - install_arch.sh (BIOS/MBR)
        - install_arch_uefi.sh (UEFI/GPT)
        - Настройка i3wm
        - Конфигурационные файлы
        - Другое
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: На каком этапе возникла ошибка?
      description: Помогает быстрее локализовать проблему
      options:
        - Подготовка диска
        - Разметка разделов
        - Форматирование
        - Установка пакетов (pacstrap)
        - Настройка системы (chroot)
        - Установка загрузчика
        - Первая загрузка
        - Настройка i3wm
        - Настройка терминала/конфигов
        - Другое
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 📋 Описание проблемы
      description: Четко опишите, что произошло
      placeholder: |
        Например: "Скрипт завершается с ошибкой при попытке создать разделы на NVMe диске"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Ожидаемое поведение
      description: Что должно было произойти?
      placeholder: |
        Например: "Скрипт должен был создать разделы и продолжить установку"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔄 Шаги для воспроизведения
      description: Как воспроизвести ошибку?
      placeholder: |
        1. Загрузиться с Arch ISO
        2. Запустить install_arch.sh
        3. Выбрать диск /dev/nvme0n1
        4. Ввести данные пользователя
        5. Ошибка возникает на этапе...
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: 🔴 Вывод ошибки
      description: Вставьте полный текст ошибки
      placeholder: |
        Вставьте здесь точный текст ошибки или вывод команды
      render: shell
    validations:
      required: true

  - type: dropdown
    id: system_type
    attributes:
      label: Тип системы
      description: Какой тип системы используется?
      options:
        - BIOS (Legacy)
        - UEFI
        - Не знаю
    validations:
      required: true

  - type: input
    id: disk_type
    attributes:
      label: 💾 Тип диска
      description: Какой диск используется?
      placeholder: "Например: SATA SSD, NVMe, HDD, USB"
    validations:
      required: true

  - type: input
    id: disk_size
    attributes:
      label: 📏 Размер диска
      description: Размер диска в GB/TB
      placeholder: "Например: 256GB, 1TB"
    validations:
      required: true

  - type: textarea
    id: lsblk_output
    attributes:
      label: 🗂️ Вывод lsblk
      description: Вставьте вывод команды lsblk
      placeholder: |
        Выполните команду: lsblk
        И вставьте результат здесь
      render: shell

  - type: textarea
    id: system_info
    attributes:
      label: 🖥️ Информация о системе
      description: Дополнительная информация о железе
      placeholder: |
        - Модель компьютера/ноутбука:
        - Процессор:
        - Оперативная память:
        - Видеокарта:
        - Возраст системы:
        - Виртуальная машина (если да, то какая):

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Дополнительная информация
      description: Любая другая полезная информация
      placeholder: |
        - Что вы уже пробовали для решения проблемы?
        - Возникала ли эта ошибка раньше?
        - Есть ли особенности конфигурации?

  - type: checkboxes
    id: help_wanted
    attributes:
      label: Готовность помочь
      description: Укажите, как вы можете помочь в решении проблемы
      options:
        - label: Могу тестировать исправления
        - label: Могу предоставить дополнительную информацию
        - label: Могу помочь с документацией
        - label: Хочу только сообщить о проблеме
