blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/samtj24/Install.sh/discussions
    about: Общие вопросы, идеи и обсуждения с сообществом
  
  - name: 📚 Arch Wiki
    url: https://wiki.archlinux.org/
    about: Официальная документация Arch Linux
  
  - name: 🎯 i3wm Documentation
    url: https://i3wm.org/docs/
    about: Официальная документация i3 window manager
  
  - name: 🏠 r/archlinux
    url: https://reddit.com/r/archlinux
    about: Reddit сообщество пользователей Arch Linux
