name: ✨ Feature Request
description: Предложить новую функцию или улучшение
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees:
  - samtj24
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение по улучшению проекта! 🚀
        Ваши идеи помогают сделать инсталлятор лучше.

  - type: checkboxes
    id: preliminary_checks
    attributes:
      label: Предварительные проверки
      description: Убедитесь, что ваша идея еще не была предложена
      options:
        - label: Я проверил [существующие Issues](https://github.com/samtj24/Install.sh/issues)
          required: true
        - label: Я просмотрел [Discussions](https://github.com/samtj24/Install.sh/discussions)
          required: true
        - label: Эта функция еще не реализована в проекте
          required: true

  - type: dropdown
    id: feature_category
    attributes:
      label: 📂 Категория улучшения
      description: К какой части проекта относится предложение?
      options:
        - Скрипт установки (install_arch.sh)
        - UEFI поддержка
        - Конфигурации i3wm
        - Терминал и приложения
        - Документация
        - GitHub Actions / CI
        - Новый скрипт/утилита
        - Другое
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Приоритет
      description: Насколько важна эта функция?
      options:
        - Низкий (было бы неплохо иметь)
        - Средний (улучшило бы пользовательский опыт)
        - Высокий (критично для многих пользователей)
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: 🔍 Какую проблему решает предложение?
      description: Опишите проблему или неудобство, которое существует сейчас
      placeholder: |
        Например: "Пользователям приходится вручную настраивать сеть после установки, 
        что неудобно для новичков..."
    validations:
      required: true

  - type: textarea
    id: solution_description
    attributes:
      label: 💡 Предлагаемое решение
      description: Как вы видите реализацию этой функции?
      placeholder: |
        Например: "Добавить в скрипт автоматическую настройку Wi-Fi через файл конфигурации
        или интерактивный выбор сети..."
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: 🔧 Детали реализации
      description: Технические детали, если у вас есть идеи
      placeholder: |
        - Какие пакеты потребуются?
        - Изменения в каких файлах?
        - Новые конфигурации?
        - Зависимости?

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Альтернативные решения
      description: Рассматривали ли вы другие способы решения проблемы?
      placeholder: |
        Например: "Можно было бы создать отдельный скрипт пост-установки, 
        но это менее удобно..."

  - type: textarea
    id: use_cases
    attributes:
      label: 🎯 Случаи использования
      description: Кому и когда будет полезна эта функция?
      placeholder: |
        - Новички в Linux
        - Пользователи с определенным типом железа
        - Специфические сценарии установки
    validations:
      required: true

  - type: checkboxes
    id: target_audience
    attributes:
      label: 👥 Целевая аудитория
      description: Кому будет полезна эта функция? (можно выбрать несколько)
      options:
        - label: Новички в Linux
        - label: Опытные пользователи Arch
        - label: Пользователи старого железа
        - label: Владельцы современных систем
        - label: Разработчики
        - label: Все пользователи

  - type: dropdown
    id: complexity
    attributes:
      label: 🧩 Сложность реализации
      description: Как вы оцениваете сложность реализации?
      options:
        - Простая (несколько строк кода)
        - Средняя (требует некоторых изменений)
        - Сложная (значительные изменения)
        - Не знаю
    validations:
      required: true

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: ⚠️ Влияние на существующую функциональность
      description: Может ли это изменение повлиять на текущих пользователей?
      options:
        - label: Это изменение обратно совместимо
        - label: Может потребоваться обновление документации
        - label: Может потребоваться миграция существующих конфигов
        - label: Это может сломать существующую функциональность

  - type: textarea
    id: mockup_example
    attributes:
      label: 📋 Пример или макет
      description: Если возможно, покажите как должна выглядеть новая функция
      placeholder: |
        Можете привести:
        - Примеры команд
        - Скриншоты интерфейса
        - Фрагменты кода
        - Схемы взаимодействия
      render: shell

  - type: checkboxes
    id: contribution_willingness
    attributes:
      label: 🤝 Готовность к участию
      description: Как вы готовы помочь в реализации?
      options:
        - label: Могу помочь с кодом
        - label: Могу помочь с тестированием
        - label: Могу помочь с документацией
        - label: Могу предоставить обратную связь
        - label: Только предлагаю идею

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Дополнительная информация
      description: Любая другая полезная информация
      placeholder: |
        - Ссылки на похожие решения
        - Документация по технологиям
        - Примеры из других проектов
