name: ❓ Question / Support
description: Задать вопрос о проекте или получить помощь
title: "[QUESTION] "
labels: ["question", "support"]
assignees:
  - samtj24
body:
  - type: markdown
    attributes:
      value: |
        Добро пожаловать! 👋 
        Мы рады помочь вам с использованием Arch Linux Auto Installer.

  - type: checkboxes
    id: documentation_check
    attributes:
      label: Проверка документации
      description: Убедитесь, что ответа нет в документации
      options:
        - label: Я прочитал [основной гайд](https://github.com/samtj24/Install.sh/blob/main/GUIDE.md)
          required: true
        - label: Я проверил [Troubleshooting](https://github.com/samtj24/Install.sh/blob/main/docs/troubleshooting.md)
          required: true
        - label: Я искал в [существующих Issues](https://github.com/samtj24/Install.sh/issues?q=is%3Aissue)
          required: true

  - type: dropdown
    id: question_category
    attributes:
      label: 📂 Категория вопроса
      description: К какой области относится ваш вопрос?
      options:
        - Установка Arch Linux
        - Настройка i3wm
        - Проблемы с железом
        - Конфигурационные файлы
        - Сетевые настройки
        - Пост-установочная настройка
        - UEFI vs BIOS
        - Выбор пакетов
        - Другое
    validations:
      required: true

  - type: dropdown
    id: experience_level
    attributes:
      label: 🎓 Уровень опыта
      description: Ваш опыт работы с Linux?
      options:
        - Полный новичок (первый раз устанавливаю Linux)
        - Начинающий (есть опыт с Ubuntu/Mint)
        - Средний (использую Linux, но первый раз Arch)
        - Продвинутый (опытный пользователь Linux)
    validations:
      required: true

  - type: textarea
    id: question_description
    attributes:
      label: ❓ Ваш вопрос
      description: Опишите максимально подробно, что вас интересует
      placeholder: |
        Например: "Я успешно установил систему, но не понимаю, как настроить автоматическое 
        подключение к Wi-Fi при загрузке. В гайде есть команды для ручного подключения, 
        но как сделать это постоянным?"
    validations:
      required: true

  - type: dropdown
    id: current_status
    attributes:
      label: 📍 Текущий статус
      description: На каком этапе вы находитесь?
      options:
        - Планирую установку
        - В процессе установки
        - Система установлена, настраиваю
        - Система работает, нужны улучшения
        - Возникли проблемы после установки
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: 🖥️ Информация о системе
      description: Расскажите о вашем железе (если релевантно)
      placeholder: |
        - Тип системы: BIOS/UEFI
        - Компьютер/ноутбук: 
        - Возраст системы:
        - Тип диска: SSD/HDD/NVMe
        - Размер диска:
        - Особенности (если есть):

  - type: textarea
    id: what_tried
    attributes:
      label: 🔧 Что уже пробовали
      description: Какие действия вы уже предпринимали?
      placeholder: |
        - Команды, которые выполняли
        - Конфигурации, которые меняли  
        - Решения, которые находили в интернете

  - type: textarea
    id: expected_outcome
    attributes:
      label: 🎯 Желаемый результат
      description: Чего вы хотите добиться?
      placeholder: |
        Например: "Хочу, чтобы при включении компьютера автоматически запускался i3wm 
        и подключался к домашней Wi-Fi сети"

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Срочность
      description: Насколько срочно нужна помощь?
      options:
        - Не срочно (изучаю для себя)
        - Умеренно (хочу разобраться в ближайшие дни)
        - Срочно (нужно для работы/учебы)
        - Критично (система не работает)
    validations:
      required: true

  - type: checkboxes
    id: help_type
    attributes:
      label: 🆘 Тип помощи
      description: Какая помощь вам нужна? (можно выбрать несколько)
      options:
        - label: Объяснение концепций
        - label: Пошаговая инструкция
        - label: Исправление конфигурации
        - label: Рекомендации по настройке
        - label: Ссылки на дополнительные ресурсы

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Дополнительная информация
      description: Любая другая информация, которая может быть полезна
      placeholder: |
        - Цель использования системы (разработка, игры, офис)
        - Ограничения или требования
        - Предпочтения в настройке
